### ISSUE TITLE
generic-optics-labels

### ISSUE THREAD

**Issue by kcsongor** [kcsongor/generic-lens#108]
Just like https://github.com/kcsongor/generic-lens/issues/102, but for the `optics` library.

I had a quick look at `LabelOptic`, and it looks like we could define a catch-all `OVERLAPPABLE` instance using `generic-optics`, which could then be naturally overridden by other means.
The issue is of course that there is already a catch-all in `optics` for better error reporting.

@phadej @arybczak @adamgundry I would be interested to hear your input on this!

**Comment by phadej** [comment]
I also briefly (with `generic-optics-lite`) used a 

```haskell
instance (HasField name Ex a, a ~ b) => LabelOptic name A_Lens Ex Ex a b where
    labelOptic = field @name
```

idiom, it's a bit of mouthful, and due how `DerivingVia` works this cannot be automated with it (as `s` is not last argument). I wish it could, then one could avoid `OVERLAPPABLE` hack for greater good.

**Comment by arybczak** [comment]
I'm reluctant to give up the OVERLAPPABLE instance of `LabelOptic` in optics-core because without it GHC errors are *really* bad.

The best I can think of is making the inclusion of this instance dependent of a flag (disabling which would be not officially supported), so that in principle people can use `optics-core -generic-label-instance` (or something) along with `generic-optics-labels` to get generic optics as labels (almost) out of the box.

**Comment by kcsongor** [comment]
Yes I agree that the existing behaviour shouldn’t be altered. Having the flag is a workable solution but I fear that it might be too intrusive and confusing, since it would mean that the available instances depend not just on imported modules, but external build flags too... I’m hoping we can find a simpler solution!

**Comment by adamgundry** [comment]
I'm really not keen on having a build flag alter the package API. I'm also not optimistic that we can retain both `OVERLAPPABLE` instances (although I'd welcome being shown a way that makes it possible). This feels unfortunately like the question of possible `IsLabel` instances for `(->)`...

What if we drop the error-reporting `LabelOptic` instance and push the generics-based one more aggressively, which implies having `optics` depend on `generic-optics`? I can see a couple of approaches to this:

Plan A:
 * Rename the existing `Optics.Label` to `Optics.Label.Core` in `optics-core`;
 * Define an orphan `OVERLAPPABLE` instance for `LabelOptic` in `generic-optics[-labels]`;
 * Make `optics` depend on `generic-optics[-labels]` and expose an `Optics.Label` module including the instance.

This means users of `optics-core` alone are potentially exposed to the bad error messages, but users of `optics` (or `optics-core` + `generic-optics[-labels]`) get all the generics goodness automatically.

Plan B:
 * Move the existing `Optics.Label` to a new package `optics-labels` which depends on `generic-optics` and provides a non-orphan `OVERLAPPABLE` instance for `LabelOptic` using generics.
 * Make `optics` depend on `optics-labels` and re-export `Optics.Label` from there.

This means `optics-core` no longer has `OverloadedLabels` support at all, so users wanting a minimal dependency footprint and `OverloadedLabels` have to pull in `optics-labels` (and hence `generic-optics`). On the other hand there is no orphan and `LabelOptic` always falls back on generics in the absence of manual instances.

What other possibilities or pros and cons am I missing?

**Comment by arybczak** [comment]
Plan A looks reasonable, but the main issue I see is that if someone is using TH and not generics, they'll get "No Generic instance for ..." error instead of "No instance for LabelOptic ..." from GHC if the label is misspelled or during refactoring.

**Comment by adamgundry** [comment]
Hmm, I had a sudden inspiration after thinking about "what would @kcsongor do?"

[This gist](https://gist.github.com/adamgundry/37e29ca9c8a30e3d94f61b0ee11d67a8) shows that contrary to my expectations, it is possible to decide whether a `Generic` instance exists for a type, using an `INCOHERENT` class instance that resolves differently depending on whether `Rep` is defined. Thus I think it *might* be possible to define a helper class for `LabelOptic`'s `OVERLAPPABLE` instance that shows an error message if there is no `Generic` instance in scope for a type, or delegates to `generic-optics` if there is such a `Generic` instance.

The main thing I'm still unsure about is whether this leads to problems with polymorphic definitions, where the incoherent instance is selected too early, leading to a failure message rather than remaining polymorphic in a `Generic a` constraint.

**Comment by adamgundry** [comment]
I've explored this idea a bit further in well-typed/optics#290, and so far it seems to be working... what am I missing?
