### ISSUE TITLE
Better support for associated data types

### ISSUE THREAD

**Issue by dwincort** [kcsongor/generic-lens#40]
Currently, associated data types don't work quite right.  It's possible to derive `Generic`, but when using the lens/prism, type unification often fails.  Consider the following simple case:

```haskell
class MyClass a where
  data AssocData a

instance MyClass Int where
  data AssocData Int = SomeData
    { val :: Int
    } deriving (Generic)
```

Then, getting the `val` field throws an error:

```
λ> getField @"val" (SomeData 3)
<interactive>:1:1: error:
    • Couldn't match type ‘generic-lens-0.5.1.0:Data.Generics.Internal.Families.Changing.ReplaceArgs
                             (AssocData Int)
                             (generic-lens-0.5.1.0:Data.Generics.Internal.Families.Changing.Unify
                                b'0 Int)’
                     with ‘AssocData Int’
        arising from a use of ‘getField’
      The type variable ‘b'0’ is ambiguous
    • In the expression: getField @"val" (SomeData 3)
      In an equation for ‘it’: it = getField @"val" (SomeData 3)
```
The error also shows up when accessing by position, but there is no error when accessing by type.  Also, the error shows up when using the prism associated with `SomeData`, but the prism associated with `Int` works fine.

**Comment by kcsongor** [comment]
Thank you for reporting this, the underlying issue is quite subtle, and it has to do with the way type-changing optics are implemented. The technique does not work well when there are type parameters with nominal roles, such as in the `AssocData` example.
This also explains why the ones that don't change types work just fine.

Sadly, there is no way (that I know of, anyway) that allows introspecting the roles of type variables, so we can't tell in general when is it "safe" to try and derive type-changing versions, and when to fall back to monomorphic ones.

The best I can think of is to export monomorphic versions of these lenses as well - would that be an appropriate solution to your problem? There would be a version of `field` that cannot change the type of the field, no matter what the structure looks like.

I'm close to finishing up a release, and I could include these monomorphic versions of optics too.

If your use-case requires a finer-grained treatment (like some parameters are nominal, but some others should be allowed to change, etc.), then please let me know and we could explore other alternatives, but those would likely require a little more thinking.

**Comment by dwincort** [comment]
Can you export `HasField'(..)` instead of just `HasField'` in `Data.Generics.Product.Fields`?  Thanks!

**Comment by kcsongor** [comment]
Thanks, well spotted! That was indeed a mistake, I've fixed it and currently updating the documentation and the changelog for the release; hopefully everything will be ready in a couple of hours.

**Comment by dwincort** [comment]
Also, how would you feel about adding a default `HasField'` instance like:
```haskell
instance {-# OVERLAPPING #-} HasField field s s a a => HasField' field s a where
  field' = field
```

In my own code, I actually have my own overlapping instance of `HasField` for a particular data type that doesn't play nice with generics (I know, this is probably like a cardinal sin in your view).  So, the reason I asked for the export of `HasField'(..)` was so that I could make a custom overlapping instance for that too.  However, (I think) if you add this default overlapping instance, then I won't need to add a custom one.

I imagine you could do the same for `AsConstructor'`.  (For what it's worth, I noticed that you're already exporting `AsConstructor'(..)`.)

I also understand if you find this hideous and a gross misuse of your library :P, in which case just exposing `HasField'(..)` should technically be enough for me.

**Comment by dwincort** [comment]
Also cool!  Good luck with the upcoming release!

**Comment by kcsongor** [comment]
It's up on hackage now, let me know if something doesn't work as expected!
