### ISSUE TITLE
AsType a Void instance is surprising

### ISSUE THREAD

**Issue by treeowl** [kcsongor/generic-lens#90]
I don't understand what you're doing well enough to know if this makes some sense in context, but the `AsType a Void` instance doesn't make sense on its own. When I ask

```haskell
_Typed = prism _1 _2
```

GHC tells me `_1 :: a -> Void`, which is surely bogus.

The `AsType Void a` instance makes sense, but it should be rewritten to be total and to propagate errors correctly:

```haskell
instance AsType Void a where
  _Typed = prism absurd Left
  injectTyped = absurd
  projectTyped = const Nothing
```

where `absurd` of course has to be written for your internal `Void`.

```haskell
absurd :: Void -> a
absurd v = case v of
```

**Comment by treeowl** [comment]
For whatever it's worth, removing the `AsType a Void` instance and rewriting the `AsType Void a` instance as suggested above does not lead to any test suite failures.

**Comment by treeowl** [comment]
Ah, I understand the context now, and how to do it right.

**Comment by kcsongor** [comment]
Thanks for pointing this out, it's clearly a sign that this part of the code is not documented well enough. Let me explain the reasoning behind these instances, and maybe we will find a more satisfactory solution.

As you say, the `AsType Void a` can be implemented just fine, but `AsType a Void` cannot, and indeed it doesn't make much sense to use that instance. However, I wrote these instances not to be used, but rather as a trick to stop implementation details from leaking into the type signatures when asking GHCi for the type of `_Typed`.
Assume that neither the `AsType Void a`, nor the `AsType a Void` instances existed. Then, unless the user has defined some overlapping instances, the only instance for the `AsType a s` class is the one defined generically. Thus, asking for the type of `_Typed`, GHC arguably unhelpfully expands its type to the following:

```
λ> :t _Typed
_Typed
  :: (ErrorUnlessOne
        a s (CollectPartialType (TupleToList a) (Rep s)),
      Defined (Rep s) (TypeError ...) (() :: Constraint), Generic s,
      ListTuple a (TupleToList a), GAsType (Rep s) (TupleToList a),
      Data.Profunctor.Choice.Choice p, Applicative f) =>
     p a (f a) -> p s (f s)
```

So, the idea is to stop GHC from doing this, and the only way I found was to introduce the (bogus) instances for `Void`. In the presence of `AsTyped Void a`, the situation is a lot better:

```
λ> :t _Typed
_Typed
  :: (AsType a s, Data.Profunctor.Choice.Choice p, Applicative f) =>
     p a (f a) -> p s (f s)
```

Great, GHC no longer eagerly expands the `AsType a s` instance. But, going a bit further, if we specify the `a` type with visible type application, we're in trouble again:

```
λ> :t _Typed @Int
_Typed @Int
  :: (ErrorUnlessOne Int s (CollectPartialType '[Int] (Rep s)),
      Defined (Rep s) (TypeError ...) (() :: Constraint), Generic s,
      GAsType (Rep s) '[Int], Data.Profunctor.Choice.Choice p,
      Applicative f) =>
     p Int (f Int) -> p s (f s)
```

This can be fixed by the `AsType a Void` instance, which is of course clearly bogus, but is not meant to be used (which is why I opted for a custom internal `Void` type, rather than using an existing one).

```
λ> :t _Typed @Int
_Typed @Int
  :: (AsType Int s, Data.Profunctor.Choice.Choice p,
      Applicative f) =>
     p Int (f Int) -> p s (f s)
```

I hope this explanation makes sense, and I will make sure that this behaviour is tested by doctests. Alternatively, if you can think of a better solution to this problem, I would also love to hear that.

**Comment by treeowl** [comment]
Thanks for the explanation. This stuff is all horrible, but it sounds like there's no better way. I'd like to use it myself in the new API I'm working on for `coercible-utils`, but I'm not so optimistic it will work properly. I have a notion there of two types being "similar", meaning they have the same type constructor and the same kind arguments. Given `Similar a b`, I'd like to infer what we can about either `a` or `b` from the other one. But given `Overlapping` instances for a `Bogus` type, won't GHC insist on checking that *neither* argument is bogus before proceeding? If so, I don't think that will do at all. [Here's the code I mean](https://github.com/sjakobi/coercible-utils/blob/ae1548465777013289c9c33f7b6a80d41f781ce3/src/Control/Newtype/Generic.hs).
